apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy
  name: envoy-svc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 10000
  selector:
    app: envoy
